# Generated by Django 4.0.2 on 2022-02-28 17:37

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', embed_video.fields.EmbedVideoField(verbose_name='Видеоурок')),
                ('full_text', models.TextField(verbose_name='Конспект урока')),
                ('homework', models.TextField(verbose_name='Домашнее задание')),
                ('added', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
