# Generated by Django 4.0.2 on 2022-04-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_topics_alter_lessons_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
