# Generated by Django 4.0.2 on 2022-04-22 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('email', models.TextField(verbose_name='Электронная почта')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотография пользователя')),
                ('review_text', models.TextField(verbose_name='Отзыв пользователя')),
                ('added', models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
    ]
